export {
  HealthCheckResponse,
  ImportGamesBody,
  ImportGamesResponse,
  ListGamesQueryParams,
  ListGamesResponse,
  GetGameParams,
  GetGameResponse,
  GetGameReplayParams,
  GetGameReplayResponse,
  AnalyzeGamesBody,
  AnalyzeGamesResponse,
  GetWeaknessesQueryParams,
  GetWeaknessesResponse,
  GetAnalysisSummaryQueryParams,
  GetAnalysisSummaryResponse,
  ListCoursesQueryParams,
  ListCoursesResponse,
  GenerateCoursesBody,
  GenerateCoursesResponse,
  GetCourseParams,
  GetCourseResponse,
  UpdateCourseProgressParams,
  UpdateCourseProgressBody,
  UpdateCourseProgressResponse,
} from "./generated/api";

export type {
  AnalysisResult,
  Course,
  CourseWithLessons,
  Game,
  GameReplay,
  GetAnalysisSummaryParams,
  GetWeaknessesParams,
  HealthStatus,
  Lesson,
  ListCoursesParams,
  ListGamesParams,
  Move,
  OpeningStat,
  PerformanceSummary,
  TimeControlStat,
  UpdateProgressBody,
  Weakness,
  WeaknessRecord,
  WeaknessReport,
} from "./generated/types";

export type {
  AnalyzeGamesBody as AnalyzeGamesBodyType,
  GenerateCoursesBody as GenerateCoursesBodyType,
  ImportGamesBody as ImportGamesBodyType,
  ImportGamesResponse as ImportGamesResponseType,
  ListCoursesResponse as ListCoursesResponseType,
  ListGamesResponse as ListGamesResponseType,
} from "./generated/types";
